/*
 * First social
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package middlewares

import (
	"github.com/go-chi/chi/v5/middleware"
	"go.uber.org/zap"
	"net/http"
	"time"
)

func Logger(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ww := middleware.NewWrapResponseWriter(w, r.ProtoMajor)

		t1 := time.Now()
		defer func() {
			zap.L().Debug("Served",
				zap.String("scheme", r.Proto),
				zap.String("path", r.URL.Path),
				zap.Duration("duration", time.Since(t1)),
				zap.Int("responseCode", ww.Status()),
				zap.Int("size", ww.BytesWritten()))
		}()

		next.ServeHTTP(ww, r)
	})
}
